title: Xadparo
email:
description: "새로 구성 중인 사이트"
baseurl: ""
url: "https://xadparo.github.io"
lang: ko
timezone: Asia/Seoul

markdown: kramdown
permalink: /:categories/:title/

theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

exclude:
  - private
  - script
  - vendor
  - .bundle
