services:
  blog:
    build:
      context: .
    working_dir: /site
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./:/site
    command: bundle exec jekyll serve --host 0.0.0.0 --livereload --force_polling

  writer:
    build:
      context: .
    working_dir: /site
    ports:
      - "4001:4001"
    volumes:
      - ./:/site
    command: bundle exec ruby script/local-writer.rb
